version: '3'

services:
  DemoApplication:
    image: simpleservice
    ports:
    - 8082:8080
  DemoApplication1:
    image: simpleservice
    ports:
    - 8085:8080
  nginx:
    image: nginx:1.17.2-alpine
    ports:
    - 81:80
    - 443:443
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - DemoApplication
    - DemoApplication1
